// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "model/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "go run model/internal/cmd/pdatagen/main.go".

package pcommon

import (
	otlpresource "go.opentelemetry.io/collector/model/internal/data/protogen/resource/v1"
	"go.opentelemetry.io/collector/model/internal/pdata"
)

type Resource struct {
	pdata.Resource
}

func NewResource() Resource {
	return Resource{pdata.NewResource(&otlpresource.Resource{})}
}

// MoveTo moves all properties from the current struct to dest
// resetting the current instance to its zero value
func (ms Resource) MoveTo(dest Resource) {
	ms.Resource.MoveTo(dest.Resource)
}

// Attributes returns the Attributes associated with this Resource.
func (ms Resource) Attributes() AttributeMap {
	return AttributeMap{ms.Resource.Attributes()}
}

// CopyTo copies all properties from the current struct to the dest.
func (ms Resource) CopyTo(dest Resource) {
	ms.Resource.CopyTo(dest.Resource)
}
